Dsukha/EOY_language_updates
CMSgov/bcda-static-site pull request #106
Opened 2020-12-15 17:43 UTC by Dave-Sukharan

### Fixes [BCDA-xxx](https://jira.cms.gov/browse/BCDA-xxx)

The end of the year is a major reassignment period. Users need to change the way they make requests to accommodate the BCDA's changes during this time. This adds language to the site that notifies users of these changes.

### Proposed Changes

1. Add NOTE to the Guide page in the /Group endpoint section
2. Add NOTE to the Build page in the first section
3. Add NOTE to the Build page in the Requesting Data section

### Change Details
![Uploading image.png…]
<img width="1142" alt="Screen Shot 2020-12-15 at 11 25 36 AM" src="https://user-images.githubusercontent.com/52724683/102251593-a9526f80-3eca-11eb-960f-0d064c199c22.png">
<img width="1153" alt="Screen Shot 2020-12-15 at 11 41 24 AM" src="https://user-images.githubusercontent.com/52724683/102251605-abb4c980-3eca-11eb-9f96-36c680577b03.png">

()

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ X] no PHI/PII is affected by this change

### Acceptance Validation

### Feedback Requested

Is this the type of language we were expecting? Should the notice be longer? Shorter? Located in a different spot?

2020-12-15 19:51 UTC, mtrang1263 commented on _includes/build/bcda_user_guide.html
> +These changes are in place to ensure that BCDA does not return any data not assigned to your organization during the transition between performance years. Please see the full details in the BCDA Goog
We're  going to wait to merge this PR until we have the link to the Google Group post, right?

2020-12-15 20:51 UTC, epfrankle requested changes
@mtrang1263 @Dave-Sukharan and I went over a new approach to this PR during our H team meeting; he'll resubmit after changing the language.

2020-12-16 04:52 UTC, Dave-Sukharan commented
@epfrankle Changes made. Added a whole new section to the Build page and the sidebar to include the End Of Year language.

@mtrang1263 All of the changes are made, but I'm sure there are merge conflicts. I still see four sections in the Home page for this branch, for example. I'd wait until we (@epfrankle ) are 110% sure about the language in these sections before resolving though.

2020-12-17 20:27 UTC, epfrankle approved these changes

2020-12-17 20:49 UTC, merged