BCDA-8113: Escape export operator and fix credential rendering
CMSgov/bcda-static-site pull request #199
Opened 2024-05-10 19:55 UTC by alex-dzeda

## 🎫 Ticket

https://jira.cms.gov/browse/BCDA-8113

## 🛠 Changes

Ensure "Try the API" credentials show properly
Escape export operator to ensure that all environments can utilize the CURL commands. 

## ℹ️ Context for reviewers

When we fixed the curl commands for windows cmd, we broke it for powershell. Now, everyone can live in harmony. 

## ✅ Acceptance Validation

To be added. 

## 🔒 Security Implications

- [ ] This PR adds a new software dependency or dependencies.
- [ ] This PR modifies or invalidates one or more of our security controls.
- [ ] This PR stores or transmits data that was not stored or transmitted before.
- [ ] This PR requires additional review of its security implications for other reasons.

If any security implications apply, add Jason Ashbaugh (GitHub username: StewGoin) as a reviewer and do not merge this PR without his approval.

2024-05-10 21:06 UTC, greg-pf approved these changes
Looks good to me

2024-05-10 21:11 UTC, austincanada approved these changes

2024-05-14 13:24 UTC, alex-dzeda commented
![image](https://github.com/CMSgov/bcda-static-site/assets/120701369/a71badaf-dcd0-43b3-b837-2006ec3abf8a)

2024-05-14 13:55 UTC, greg-pf requested changes
Requesting a change from `Powershell` to `PowerShell`, otherwise looks good

2024-05-14 13:55 UTC, greg-pf commented on _includes/guide/try_the_api.html
> +	For more detail for each of these steps and specific information for retrieving production data, see the <a href=/build.html target="_self" class="in-text__link"> Building Your Application</a> page.
```suggestion
	For more detail for each of these steps and specific information for retrieving production data, see the <a href=/build.html target="_self" class="in-text__link"> Building Your Application</a> page. For this short demo, follow along in your Terminal window or through an application such as Postman. PowerShell users will need to replace backslash characters \ with backticks ` to properly escape the $export operation.
```

2024-05-14 13:57 UTC, greg-pf approved these changes
Thanks! :shipit:

2024-05-14 14:04 UTC, merged