Plk/bcda 3769
CMSgov/bcda-static-site pull request #83
Opened 2020-10-01 13:24 UTC by PatKelsh

### Fixes [BCDA-3769](https://jira.cms.gov/browse/BCDA-3769)

Migrated over stylesheets from DPC static site. Now using node package of CMS design sytem

### Proposed Changes

* Added CMS design system
* Updated jekyll config for sass precompile
* Removed old stylesheets

### Change Details

### Security Implications

- [x] new software dependencies

The new CMS design system node installation

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [x] no PHI/PII is affected by this change

### Acceptance Validation

Insert this into the top of the `_layouts/home.html` file and start the server. Should see a spinner at the top of the page.
```<div class="ds-l-row">
    <span class="ds-c-spinner" aria-valuetext="Loading" role="progressbar"></span>
  </div>
```

### Feedback Requested

Do we want to go in this direction and copy DPC completely or would like to keep the old way of just copying the stylesheets from the CMS design system into the `_assests` directory?

2020-10-01 14:29 UTC, jeffcorpuz commented on assets/css/static-main.scss
> +*/
will this be added later? would you mind commenting out why this is commented out?

2020-10-01 14:30 UTC, jeffcorpuz commented on assets/css/static-main.scss
> +*/
likewise, can you comment why this is commented out?

2020-10-01 18:55 UTC, mtrang1263 requested changes
A couple notes:
1. Can we update the PR title to give a summary of these changes?
2. We should switch the base branch from `master` to `static-site-glowup`?

2020-10-02 14:47 UTC, mtrang1263 approved these changes
LGTM!

2020-10-02 16:18 UTC, merged